# Use the PHP 8.2 image with Apache (replace with actual image once available)
FROM php:8.2-apache

# Set the working directory
WORKDIR /var/www/html

# Copy the PHP application files into the container
COPY . .

# Install necessary extensions (example: PDO MySQL)
RUN docker-php-ext-install pdo pdo_mysql
RUN docker-php-ext-install mysqli
RUN pecl install redis \
        && docker-php-ext-enable redis

# Expose port 80
EXPOSE 80

# Start Apache and serve the PHP application
CMD ["apache2-foreground"]
